In [1]:
import numpy as np
import pandas as pd

In [2]:
books= pd.read_csv('Books.csv')
users= pd.read_csv('users.csv')
ratings= pd.read_csv('ratings.csv')

C:\Users\galah\AppData\Local\Temp\ipykernel_27228\1141042846.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books= pd.read_csv('Books.csv')

In [10]:
ratings.head()

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [4]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [5]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [6]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [8]:
books.duplicated().sum()

0

In [9]:
users.duplicated().sum()

0

In [11]:
user_review_count=ratings.groupby('User-ID').size()

In [12]:
user_review_count_50=user_review_count[user_review_count>50]

In [15]:
num_user=len(user_review_count_50)

In [16]:
print(num_user)

3371

In [18]:
filtered_rating=ratings[ratings["User-ID"].isin(user_review_count_50)]

In [20]:
filtered_rating.to_csv('filtered_ratings.csv',index=False)

In [21]:
users.head()

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN

In [22]:
books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [26]:
filtered_rating=pd.read_csv('filtered_ratings.csv')

In [27]:
filtered_rating.head()

   User-ID        ISBN  Book-Rating
0       51  0440225701            9
1       53  0060914068            3
2       53  0156047624           10
3       53  0245542957            6
4       53  0380715899            9

In [30]:
filtered_user_ids = filtered_rating['User-ID'].unique()
filtered_isbns = filtered_rating['ISBN'].unique()
 
filtered_users = users[users['User-ID'].isin(filtered_user_ids)]
filtered_books = books[books['ISBN'].isin(filtered_isbns)]
 
filtered_users.to_csv('filtered_users.csv', index=False)
filtered_books.to_csv('filtered_books.csv', index=False)

In [32]:
filtered_books=pd.read_csv('filtered_books.csv')

In [33]:
filtered_users=pd.read_csv('filtered_users.csv')

In [35]:
filtered_books.head()

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0440234743,The Testament,John Grisham,1999,Dell,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...,http://images.amazon.com/images/P/0440234743.0...
1,0971880107,Wild Animus,Rich Shapero,2004,Too Far,http://images.amazon.com/images/P/0971880107.0...,http://images.amazon.com/images/P/0971880107.0...,http://images.amazon.com/images/P/0971880107.0...
2,0345417623,Timeline,MICHAEL CRICHTON,2000,Ballantine Books,http://images.amazon.com/images/P/0345417623.0...,http://images.amazon.com/images/P/0345417623.0...,http://images.amazon.com/images/P/0345417623.0...
3,0449005615,Seabiscuit: An American Legend,LAURA HILLENBRAND,2002,Ballantine Books,http://images.amazon.com/images/P/0449005615.0...,http://images.amazon.com/images/P/0449005615.0...,http://images.amazon.com/images/P/0449005615.0...
4,0671888587,I'll Be Seeing You,Mary Higgins Clark,1994,Pocket,http://images.amazon.com/images/P/0671888587.0...,http://images.amazon.com/images/P/0671888587.0...,http://images.amazon.com/images/P/0671888587.0...

In [36]:
books.rename(columns={
    "Book-Title":"title",
    "Book-Author":"author",
    "Year-Of-Publication": "year",
    "Publisher":"publisher",
    "Image-URL-S":"img_url"
},inplace=True)

In [37]:
books.head()

,ISBN,title,author,year,publisher,img_url,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [40]:
ratings.rename(columns={
"User-ID" : "user_id" ,
"Book-Rating": "rating"}, inplace=True)

In [41]:
ratings.head()

   user_id        ISBN  rating
0   276725  034545104X       0
1   276726  0155061224       5
2   276727  0446520802       0
3   276729  052165615X       3
4   276729  0521795028       6

In [100]:
x=ratings['user_id'].value_counts()>200

In [43]:
x

user_id
11676      True
198711     True
153662     True
98391      True
35859      True
          ...
116180    False
116166    False
116154    False
116137    False
276723    False
Name: count, Length: 105283, dtype: bool

In [45]:
x[x].shape

(1825,)

In [46]:
y=x[x].index

In [47]:
y

Index([ 11676, 198711, 153662,  98391,  35859, 212898, 278418,  76352, 110973,
       235105,
       ...
       238186,  99441, 187410, 262070,  70183,  40553,  39345, 266283, 189666,
       140879],
      dtype='int64', name='user_id', length=1825)

In [48]:
ratings=ratings[ratings['user_id'].isin(y)]

In [51]:
ratings.shape

(656605, 3)

In [52]:
rating_with_books=ratings.merge(books,on="ISBN")

In [53]:
rating_with_books.shape

(604854, 10)

In [54]:
num_rating=rating_with_books.groupby('title')['rating'].count().reset_index()

In [57]:
num_rating.rename(columns={"rating":"num_of_rating"},inplace=True)

In [59]:
final_rating=rating_with_books.merge(num_rating,on='title')

In [61]:
final_rating= final_rating[final_rating['num_of_rating']>=50]

In [64]:
final_rating.sample(10)

,user_id,ISBN,rating,title,author,year,publisher,img_url,Image-URL-M,Image-URL-L,num_of_rating
343323,159376,0743407083,0,Grand Avenue,Joy Fielding,2002,Pocket Star,http://images.amazon.com/images/P/0743407083.0...,http://images.amazon.com/images/P/0743407083.0...,http://images.amazon.com/images/P/0743407083.0...,51
158524,73394,0380814021,0,The Princess Diaries,Meg Cabot,2001,HarperTrophy,http://images.amazon.com/images/P/0380814021.0...,http://images.amazon.com/images/P/0380814021.0...,http://images.amazon.com/images/P/0380814021.0...,60
103242,41841,0671021001,0,She's Come Undone (Oprah's Book Club),Wally Lamb,1998,Pocket,http://images.amazon.com/images/P/0671021001.0...,http://images.amazon.com/images/P/0671021001.0...,http://images.amazon.com/images/P/0671021001.0...,185
247734,113519,0805063897,0,Nickel and Dimed: On (Not) Getting By in America,Barbara Ehrenreich,2002,Owl Books,http://images.amazon.com/images/P/0805063897.0...,http://images.amazon.com/images/P/0805063897.0...,http://images.amazon.com/images/P/0805063897.0...,148
418603,195469,0446525774,0,Saving Faith,David Baldacci,1999,Warner Books,http://images.amazon.com/images/P/0446525774.0...,http://images.amazon.com/images/P/0446525774.0...,http://images.amazon.com/images/P/0446525774.0...,112
93687,36907,0385721676,0,Oryx and Crake,MARGARET ATWOOD,2004,Anchor,http://images.amazon.com/images/P/0385721676.0...,http://images.amazon.com/images/P/0385721676.0...,http://images.amazon.com/images/P/0385721676.0...,73
355490,166123,0743460529,0,Daddy's Little Girl,Mary Higgins Clark,2003,Pocket,http://images.amazon.com/images/P/0743460529.0...,http://images.amazon.com/images/P/0743460529.0...,http://images.amazon.com/images/P/0743460529.0...,115
383227,177458,0676973922,0,The Fourth Hand,John Irving,2001,Knopf Canada,http://images.amazon.com/images/P/0676973922.0...,http://images.amazon.com/images/P/0676973922.0...,http://images.amazon.com/images/P/0676973922.0...,69
311655,145369,0425113884,0,Mortal Fear,Robin Cook,1989,Berkley Publishing Group,http://images.amazon.com/images/P/0425113884.0...,http://images.amazon.com/images/P/0425113884.0...,http://images.amazon.com/images/P/0425113884.0...,76
50556,21364,0345443284,0,While I Was Gone,Sue Miller,1999,Ballantine Books,http://images.amazon.com/images/P/0345443284.0...,http://images.amazon.com/images/P/0345443284.0...,http://images.amazon.com/images/P/0345443284.0...,188

In [66]:
final_rating.drop_duplicates(['user_id','title'],inplace=True)

C:\Users\galah\AppData\Local\Temp\ipykernel_27228\1573401051.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_rating.drop_duplicates(['user_id','title'],inplace=True)

In [68]:
final_rating.shape

(97962, 11)

In [69]:
book_pivot = final_rating.pivot_table(columns='user_id',index='title',values='rating')

In [73]:
book_pivot

user_id,183,254,507,882,1424,1435,1733,1903,2033,2110,...,276018,276463,276680,276925,277427,277478,277639,278137,278188,278418
title,,,,,,,,,,,,,,,,,,,,,
1984,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2010: Odyssey Two,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
204 Rosewood Lane,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24 Hours,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,10.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [72]:
book_pivot.fillna(0,inplace=True)

In [ ]:
from scipy.sparse import csr_matrix

In [75]:
book_sparse=csr_matrix(book_pivot)

In [76]:
book_sparse

<1094x1794 sparse matrix of type '<class 'numpy.float64'>'
	with 26903 stored elements in Compressed Sparse Row format>

In [77]:
from sklearn.neighbors import  NearestNeighbors

In [78]:
model=NearestNeighbors(algorithm='brute')

In [79]:
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [80]:
distance, suggestion = model.kneighbors(book_pivot.iloc[254,:].values.reshape(1,-1),n_neighbors=6)

In [81]:
distance

array([[ 0.        , 49.81967483, 50.009999  , 50.18964037, 50.23942675,
        50.32891813]])

In [82]:
suggestion

array([[254, 916, 335, 561, 939, 322]], dtype=int64)

In [86]:
books_name=book_pivot.index

In [85]:
for i in range(len(suggestion)):
    print(book_pivot.index[suggestion[i]])

Index(['Eats, Shoots &amp; Leaves: The Zero Tolerance Approach to Punctuation',
       'The Playboy', 'Ground Zero and Beyond', 'Personal Injuries',
       'The Road to Omaha', 'Get Shorty'],
      dtype='object', name='title')

import

In [87]:
import pickle
pickle.dump(model, open('artifacts/model.pkl','wb'))
pickle.dump(books_name, open('artifacts/books_name.pkl','wb'))
pickle.dump(final_rating, open('artifacts/final_rating.pkl','wb'))
pickle.dump(book_pivot, open('artifacts/book_pivot.pkl','wb'))

In [97]:
def recommend_book(book_name):
    book_id=np.where(book_pivot.index==book_name)[0][0]
    distance, suggestion = model.kneighbors(book_pivot.iloc[book_id,:].values.reshape(1,-1),n_neighbors=6)
    for i in range(len(suggestion)):
        books=book_pivot.index[suggestion[i]]
        for j in books:
            print(j)

In [101]:
book_name='Harry Potter and the Chamber of Secrets (Book 2)'
recommend_book(book_name)

Harry Potter and the Chamber of Secrets (Book 2)
Harry Potter and the Goblet of Fire (Book 4)
Harry Potter and the Prisoner of Azkaban (Book 3)
Harry Potter and the Sorcerer's Stone (Book 1)
The Charm School
The Road to Omaha